module.exports = {
	'likes': '{likes, number} Me gusta',
	'logout': 'Salir',
	'english': 'Inglés',
	'spanish': 'Español',
	'signup.subheading': 'Regístrate para poder ver las fotos de tus amigos estudiando en Platzi',
	'signin.subheading': 'Inicia sesión para poder ver las fotos de tus amigos estudiando en Platzi',
	'signup.facebook': 'Iniciar sesión con Facebook',
	'signup.text': 'Iniciar sesión',
	'email': 'Correo electrónico',
	'username': 'Nombre de usuario',
	'fullname': 'Nombre completo',
	'password': 'Contraseña',
	'signup.call-to-action': 'Regístrate',
	'signup.have-account': '¿Tienes una cuenta?',
	'signin': 'Entrar',
	'signin.not-have-account': '¿No tienes una cuenta?',
	'language': 'Idioma',
	'upload-picture': 'Subir foto',
	'upload': 'Subir'
}